url: "https://Prueba2.github.io" 
baseurl: "/"

# Site settings
title: WineBot
email: malttz15@gmail.com
description: "En este repositorio se aloja el código del sistema experto para recomendación de vinos conforme a varias preferencias elegibles por el usuario. Su modalidad de uso puede ser por voz o escrita."


# Team names, titles and social links
#stack-overflow
people:
- name: Mario Rosas Otero
  pic: Mario.jpeg
  position: Desarrollador
  social:
    - title: twitter
      url: https://twitter.com/Mariuki1
    - title: facebook
      url: https://www.facebook.com/djmaletas
    - title: linkedin
      url: https://www.linkedin.com/in/mario-rosas-443726187/

- name: Natalia Sanchez
  pic: Natalia.jpeg
  position: Desarrollador
  social:
    - title: twitter
      url: https://twitter.com/Natalia56102779
    - title: facebook
      url: https://www.facebook.com/natalia.sanchezpatino.3
    - title: linkedin
      url: https://www.linkedin.com/in/natalia-s-ba061810a/

- name: Ruben Martinez
  pic: Rubs.jpg
  position: Experto Vinícola
  social:
    - title: twitter
      url: https://twitter.com/RubenMte1
    - title: facebook
      url: https://www.facebook.com/ruben.mte
    - title: instagram
      url: https://www.instagram.com/rubmte/?hl=en


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#   - title: twitter
#     url: https://twitter.com/ClubesCienciaMx
#   - title: facebook
#     url: https://www.facebook.com/clubesdecienciamx
#   - title: youtube
#     url: https://www.youtube.com/user/ClubesDeCienciaMx
  - title: github
    url: https://github.com/NM-Labs/WineBot/

# Build settings
markdown: kramdown
permalink: pretty
